"""
seed_data.py
Static structured data derived from the rules.
This data drives the game engine directly — it is NOT parsed from text,
but hand-crafted from the rules for maximum accuracy.
"""

from typing import Any

# ── GAME PHASES ──────────────────────────────────────────────────────────────
# phase_order uses integers; attack sub-steps use 5.1 → 5.5

GAME_PHASES: list[dict[str, Any]] = [
    {
        "phase_key":   "turn_start",
        "phase_name":  "Start of Turn Step",
        "phase_order": 1,
        "is_optional": False,
        "can_repeat":  False,
        "rule_ref":    "501",
        "description": "Turn player untaps all cards; start-of-turn triggers resolve.",
    },
    {
        "phase_key":   "draw",
        "phase_name":  "Draw Step",
        "phase_order": 2,
        "is_optional": False,
        "can_repeat":  False,
        "rule_ref":    "502",
        "description": "Turn player draws 1 card (skipped on first player's first turn).",
    },
    {
        "phase_key":   "mana_charge",
        "phase_name":  "Mana Charge Step",
        "phase_order": 3,
        "is_optional": True,
        "can_repeat":  False,
        "rule_ref":    "503",
        "description": "Turn player may charge 1 card from hand into Mana Zone.",
    },
    {
        "phase_key":   "main",
        "phase_name":  "Main Step",
        "phase_order": 4,
        "is_optional": True,
        "can_repeat":  False,
        "rule_ref":    "504",
        "description": "Turn player may play cards and cross Cross Gears.",
    },
    # ── Attack sub-steps ─────────────────────────────────────────────────────
    {
        "phase_key":   "attack_declare",
        "phase_name":  "Specify Attacking Creature Step",
        "phase_order": 5,
        "is_optional": True,
        "can_repeat":  True,
        "rule_ref":    "506",
        "description": "Turn player declares an attacking creature and its target.",
    },
    {
        "phase_key":   "block_declare",
        "phase_name":  "Specify Blocking Creature Step",
        "phase_order": 6,
        "is_optional": True,
        "can_repeat":  True,
        "rule_ref":    "507",
        "description": "Non-turn player may use Blocker or Guardman to redirect attack.",
    },
    {
        "phase_key":   "battle",
        "phase_name":  "Battle Step",
        "phase_order": 7,
        "is_optional": True,
        "can_repeat":  True,
        "rule_ref":    "508",
        "description": "Battle occurs if attack targets a creature.",
    },
    {
        "phase_key":   "direct_attack",
        "phase_name":  "Direct Attack Step",
        "phase_order": 8,
        "is_optional": True,
        "can_repeat":  True,
        "rule_ref":    "509",
        "description": "If attack target is the player, shields are broken or player loses.",
    },
    {
        "phase_key":   "attack_end",
        "phase_name":  "End of Attack Step",
        "phase_order": 9,
        "is_optional": True,
        "can_repeat":  True,
        "rule_ref":    "510",
        "description": "End-of-attack triggers fire; during-attack effects expire.",
    },
    {
        "phase_key":   "turn_end",
        "phase_name":  "End of Turn Step",
        "phase_order": 10,
        "is_optional": False,
        "can_repeat":  False,
        "rule_ref":    "511",
        "description": "End-of-turn triggers resolve; temporary effects expire.",
    },
]


# ── PHASE ACTIONS ────────────────────────────────────────────────────────────
# keyed by phase_key; each list element becomes one dm_phase_actions row

PHASE_ACTIONS: dict[str, list[dict[str, Any]]] = {
    "turn_start": [
        {
            "action_order": 1,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "untap_all",
            "condition":    None,
            "rule_ref":     "501.1",
            "description":  "Untap all turn player's cards in Battle Zone and Mana Zone simultaneously.",
        },
        {
            "action_order": 2,
            "actor":        "turn_player",
            "action_type":  "optional",
            "action_key":   "silent_skill_activate",
            "condition":    "creature_has_silent_skill",
            "rule_ref":     "501.1a",
            "description":  "May choose not to untap a creature with Silent Skill.",
        },
        {
            "action_order": 3,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "resolve_start_of_turn_triggers",
            "condition":    None,
            "rule_ref":     "501.2",
            "description":  "All 'at the beginning of the turn' triggered abilities resolve.",
        },
    ],
    "draw": [
        {
            "action_order": 1,
            "actor":        "turn_player",
            "action_type":  "mandatory",
            "action_key":   "draw_card",
            "condition":    "not_first_turn_of_game",
            "rule_ref":     "502.1",
            "description":  "Turn player draws 1 card from deck.",
        },
    ],
    "mana_charge": [
        {
            "action_order": 1,
            "actor":        "turn_player",
            "action_type":  "optional",
            "action_key":   "charge_mana",
            "condition":    "has_card_in_hand",
            "rule_ref":     "503.1",
            "description":  "Place 1 card from hand into Mana Zone face-down (upside-down).",
        },
    ],
    "main": [
        {
            "action_order": 1,
            "actor":        "turn_player",
            "action_type":  "optional",
            "action_key":   "play_card",
            "condition":    "can_afford_card",
            "rule_ref":     "504.1",
            "description":  "Summon creature / cast spell / generate cross gear / deploy field / use aura / use tamaseed.",
        },
        {
            "action_order": 2,
            "actor":        "turn_player",
            "action_type":  "optional",
            "action_key":   "cross_gear",
            "condition":    "cross_gear_in_battle_zone",
            "rule_ref":     "504.2",
            "description":  "Pay mana cost again to cross a Cross Gear onto a creature.",
        },
    ],
    "attack_declare": [
        {
            "action_order": 1,
            "actor":        "turn_player",
            "action_type":  "optional",
            "action_key":   "declare_attacker",
            "condition":    "has_untapped_creature_since_turn_start",
            "rule_ref":     "506.1",
            "description":  "Choose an untapped creature to attack; tap it; choose target (player or tapped creature).",
        },
        {
            "action_order": 2,
            "actor":        "turn_player",
            "action_type":  "conditional",
            "action_key":   "declare_ninja_strike_revolution_change",
            "condition":    "triggered_ability_requires_declaration",
            "rule_ref":     "506.3b",
            "description":  "Declare use of Ninja Strike, Revolution Change, etc.",
        },
        {
            "action_order": 3,
            "actor":        "non_turn_player",
            "action_type":  "conditional",
            "action_key":   "declare_ninja_strike_revolution_change",
            "condition":    "triggered_ability_requires_declaration",
            "rule_ref":     "506.3d",
            "description":  "Non-turn player declares Ninja Strike, G-Strike, etc.",
        },
    ],
    "block_declare": [
        {
            "action_order": 1,
            "actor":        "non_turn_player",
            "action_type":  "optional",
            "action_key":   "declare_blocker",
            "condition":    "has_untapped_blocker",
            "rule_ref":     "507.1",
            "description":  "Choose creature(s) with Blocker/Guardman to redirect attack.",
        },
        {
            "action_order": 2,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "resolve_block_abilities",
            "condition":    "blocker_declared",
            "rule_ref":     "507.2",
            "description":  "Resolve blocker abilities in non-turn-player's chosen order.",
        },
    ],
    "battle": [
        {
            "action_order": 1,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "compare_power",
            "condition":    "attacking_creature_vs_creature",
            "rule_ref":     "508.1",
            "description":  "Compare power of attacking and blocking creatures; loser(s) destroyed.",
        },
    ],
    "direct_attack": [
        {
            "action_order": 1,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "check_shields",
            "condition":    "no_shields_remaining",
            "rule_ref":     "509.1",
            "description":  "If non-turn player has 0 shields, they lose the game.",
        },
        {
            "action_order": 2,
            "actor":        "turn_player",
            "action_type":  "mandatory",
            "action_key":   "choose_shields_to_break",
            "condition":    "shields_exist",
            "rule_ref":     "509.3",
            "description":  "Choose shields to break equal to breaker count.",
        },
        {
            "action_order": 3,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "break_shields",
            "condition":    "shields_chosen",
            "rule_ref":     "509.5",
            "description":  "Move chosen shields to non-turn player's hand.",
        },
        {
            "action_order": 4,
            "actor":        "non_turn_player",
            "action_type":  "optional",
            "action_key":   "declare_s_trigger",
            "condition":    "broken_shield_has_s_trigger",
            "rule_ref":     "509.5a",
            "description":  "Declare S-Trigger / G-Strike / S-Back / Sabaki Z.",
        },
        {
            "action_order": 5,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "resolve_shield_triggers",
            "condition":    "triggers_declared",
            "rule_ref":     "509.5e",
            "description":  "Resolve S-Triggers, G-Strikes, S-Backs, Sabaki Z in chosen order.",
        },
    ],
    "attack_end": [
        {
            "action_order": 1,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "resolve_end_of_attack_triggers",
            "condition":    None,
            "rule_ref":     "510.1",
            "description":  "All 'at the end of the attack' triggers resolve.",
        },
        {
            "action_order": 2,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "expire_attack_effects",
            "condition":    None,
            "rule_ref":     "510.2",
            "description":  "Expire 'during an attack' and 'while blocking' effects.",
        },
    ],
    "turn_end": [
        {
            "action_order": 1,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "resolve_end_of_turn_triggers",
            "condition":    None,
            "rule_ref":     "511.1",
            "description":  "All 'at the end of turn' triggers resolve (turn-player first).",
        },
        {
            "action_order": 2,
            "actor":        "game",
            "action_type":  "mandatory",
            "action_key":   "expire_turn_effects",
            "condition":    None,
            "rule_ref":     "511.2",
            "description":  "Expire 'during this turn' and 'until end of turn' effects.",
        },
    ],
}


# ── STATE-BASED ACTIONS ──────────────────────────────────────────────────────
# Exactly mirrors rules 703.4a–703.4m

STATE_BASED_ACTIONS: list[dict[str, Any]] = [
    {
        "rule_number":   "703.4a",
        "action_key":    "direct_attack_loss",
        "description":   "Player who received a Direct Attack with no shields loses.",
        "condition_json": {
            "event":      "direct_attack",
            "subject":    "non_turn_player",
            "shields_eq": 0,
        },
        "effect_json": {"action": "lose_game", "target": "non_turn_player"},
        "priority":   1,
    },
    {
        "rule_number":   "703.4b",
        "action_key":    "deck_out_loss",
        "description":   "Player whose deck has 0 cards loses.",
        "condition_json": {
            "zone":     "deck",
            "count_eq": 0,
            "subject":  "player",
        },
        "effect_json": {"action": "lose_game", "target": "that_player"},
        "priority":   2,
    },
    {
        "rule_number":   "703.4c",
        "action_key":    "destroy_zero_power",
        "description":   "Creature with power 0 or less is destroyed.",
        "condition_json": {
            "zone":      "battle_zone",
            "type":      "creature",
            "power_lte": 0,
        },
        "effect_json": {"action": "destroy", "target": "self"},
        "priority":   10,
    },
    {
        "rule_number":   "703.4d",
        "action_key":    "destroy_battle_loser",
        "description":   "Creature that lost a battle is destroyed.",
        "condition_json": {
            "event": "battle_resolved",
            "result": "lost_battle",
        },
        "effect_json": {"action": "destroy", "target": "battle_loser"},
        "priority":   10,
    },
    {
        "rule_number":   "703.4e",
        "action_key":    "god_link_break_invalid",
        "description":   "If linked God information becomes invalid, the link detaches.",
        "condition_json": {
            "type":      "god",
            "link_valid": False,
        },
        "effect_json": {"action": "detach_link", "target": "self"},
        "priority":   15,
    },
    {
        "rule_number":   "703.4f",
        "action_key":    "god_leave_one_card",
        "description":   "When Gods leave the Battle Zone, only 1 of them leaves.",
        "condition_json": {
            "type":  "god",
            "event": "leave_battle_zone",
        },
        "effect_json": {"action": "leave_battle_zone", "count": 1},
        "priority":   15,
    },
    {
        "rule_number":   "703.4g",
        "action_key":    "standalone_cell_to_graveyard",
        "description":   "A standalone Psychic/Dragheart Cell in the Battle Zone goes to Graveyard.",
        "condition_json": {
            "zone":        "battle_zone",
            "type":        "cell",
            "standalone":  True,
        },
        "effect_json": {"action": "move_to_zone", "destination": "graveyard"},
        "priority":   10,
    },
    {
        "rule_number":   "703.4h",
        "action_key":    "evolution_reconstruction",
        "description":   "When only the top card of an Evolution Creature leaves, reconstruct.",
        "condition_json": {
            "type":  "evolution_creature",
            "event": "top_card_only_leaves",
        },
        "effect_json": {"action": "reconstruct", "target": "underlying_cards"},
        "priority":   12,
    },
    {
        "rule_number":   "703.4i",
        "action_key":    "invalid_type_to_graveyard",
        "description":   "Face-up card in Battle Zone with no valid type goes to Graveyard.",
        "condition_json": {
            "zone":          "battle_zone",
            "face_up":       True,
            "valid_type":    False,
        },
        "effect_json": {"action": "move_to_zone", "destination": "graveyard"},
        "priority":   8,
    },
    {
        "rule_number":   "703.4j",
        "action_key":    "command_removes_seal",
        "description":   "When a Command enters the Battle Zone, its owner removes 1 seal of the same civilization.",
        "condition_json": {
            "event":         "enter_battle_zone",
            "type":          "command",
            "sealed_cards_with_same_civilization": True,
        },
        "effect_json": {"action": "remove_seal", "count": 1, "civilization": "same_as_command"},
        "priority":   12,
    },
    {
        "rule_number":   "703.4k",
        "action_key":    "castle_graveyard_on_shield_leave",
        "description":   "When a fortified shield leaves the Shield Zone, the Castle goes to Graveyard.",
        "condition_json": {
            "event": "leave_shield_zone",
            "type":  "fortified_shield",
        },
        "effect_json": {"action": "move_to_zone", "target": "castle", "destination": "graveyard"},
        "priority":   15,
    },
    {
        "rule_number":   "703.4l",
        "action_key":    "d2_field_replace",
        "description":   "When a second D2 Field enters the Battle Zone, the first is destroyed.",
        "condition_json": {
            "event":             "enter_battle_zone",
            "type":              "d2_field",
            "existing_d2_field": True,
        },
        "effect_json": {"action": "move_to_zone", "target": "existing_d2_field", "destination": "graveyard"},
        "priority":   12,
    },
    {
        "rule_number":   "703.4m",
        "action_key":    "standalone_weapon_to_graveyard",
        "description":   "A standalone Weapon in the Battle Zone is placed in the Graveyard.",
        "condition_json": {
            "zone":       "battle_zone",
            "type":       "weapon",
            "standalone": True,
        },
        "effect_json": {"action": "move_to_zone", "destination": "graveyard"},
        "priority":   10,
    },
]


# ── KEYWORDS ─────────────────────────────────────────────────────────────────
# Core keywords extracted from the rules + common DM card text

KEYWORDS: list[dict[str, Any]] = [
    # ── Creature battle keywords ──────────────────────────────────────────────
    {
        "name":  "Speed Attacker",
        "short_desc": "Can attack the turn it's summoned (ignores summoning sickness).",
        "full_rule_ref": "101.2",
        "overrides_summoning_sickness": True,
        "is_static": True,
        "usable_in_phase": ["attack"],
    },
    {
        "name":  "Blocker",
        "short_desc": "Can intercept an attacking creature to redirect the attack.",
        "full_rule_ref": "701.12a",
        "is_activated": True,
        "usable_in_phase": ["block_declare"],
    },
    {
        "name":  "Slayer",
        "short_desc": "When this creature battles, the battling opponent is destroyed.",
        "full_rule_ref": None,
        "is_triggered": True,
        "usable_in_phase": ["battle"],
    },
    {
        "name":  "Double Breaker",
        "short_desc": "Breaks 2 shields instead of 1 when attacking.",
        "full_rule_ref": "509.2b",
        "is_static": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "Triple Breaker",
        "short_desc": "Breaks 3 shields when attacking.",
        "full_rule_ref": "509.2b",
        "is_static": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "World Breaker",
        "short_desc": "Breaks all of the opponent's shields when attacking.",
        "full_rule_ref": "509.2b",
        "is_static": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "Power Attacker",
        "short_desc": "Gains additional power while attacking.",
        "full_rule_ref": None,
        "is_static": True,
        "usable_in_phase": ["attack"],
    },
    {
        "name":  "Guardman",
        "short_desc": "When an opponent's creature attacks one of your other creatures, can redirect attack to this creature.",
        "full_rule_ref": "507.1a",
        "is_activated": True,
        "usable_in_phase": ["block_declare"],
    },
    # ── Shield trigger keywords ───────────────────────────────────────────────
    {
        "name":  "S-Trigger",
        "short_desc": "When this shield is broken, may use this card for free.",
        "full_rule_ref": "112.3a",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "S-Back",
        "short_desc": "When a specified card is broken as a shield, discard this card from hand to use it for free.",
        "full_rule_ref": "112.3b",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "G-Strike",
        "short_desc": "When this shield is broken, reveal it to prevent 1 opponent's creature from attacking.",
        "full_rule_ref": "509.5b",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["direct_attack"],
    },
    {
        "name":  "Sabaki Z",
        "short_desc": "When a Judgment Crest card is broken, discard this from hand to use it for free.",
        "full_rule_ref": "112.3d",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["direct_attack"],
    },
    # ── Summoning / cost keywords ─────────────────────────────────────────────
    {
        "name":  "Ninja Strike",
        "short_desc": "When a creature attacks, if you have the specified mana, summon this for free.",
        "full_rule_ref": "112.3c",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["attack_declare"],
    },
    {
        "name":  "Revolution Change",
        "short_desc": "When this creature attacks, swap it with a specified creature from hand for free.",
        "full_rule_ref": "603.2e",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["attack_declare"],
    },
    {
        "name":  "G-Zero",
        "short_desc": "If the specified condition is met, summon or cast for free.",
        "full_rule_ref": "112.3e",
        "is_activated": True,
        "usable_in_phase": ["main"],
    },
    {
        "name":  "Attack Chance",
        "short_desc": "When the specified creature attacks, cast this spell for free.",
        "full_rule_ref": "112.3f",
        "is_triggered": True,
        "requires_declaration": True,
        "usable_in_phase": ["attack_declare"],
    },
    {
        "name":  "Sympathy",
        "short_desc": "Cost reduced by the number of specified creatures you have.",
        "full_rule_ref": "110.4e",
        "is_static": True,
        "usable_in_phase": ["main"],
    },
    {
        "name":  "Mana Burst",
        "short_desc": "When charged into Mana Zone, may cast this spell for free if condition met.",
        "full_rule_ref": "110.4b",
        "is_triggered": True,
        "usable_in_phase": ["mana_charge"],
    },
    # ── Special summon / evolution keywords ──────────────────────────────────
    {
        "name":  "Silent Skill",
        "short_desc": "At start of your turn, may keep this tapped to activate a special ability.",
        "full_rule_ref": "501.1a",
        "is_activated": True,
        "usable_in_phase": ["turn_start"],
    },
    {
        "name":  "NEO Evolution",
        "short_desc": "Can be placed on top of a non-evolution creature as an evolution creature.",
        "full_rule_ref": "802.1",
        "is_static": True,
        "overrides_summoning_sickness": True,
        "usable_in_phase": ["main"],
    },
    {
        "name":  "GR Summon",
        "short_desc": "Summon the top card of your Ultra GR Zone for free.",
        "full_rule_ref": "701.30a",
        "is_activated": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Dragsolution",
        "short_desc": "Flip this Dragheart to its creature face.",
        "full_rule_ref": "701.22a",
        "is_triggered": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Dragon Evasion",
        "short_desc": "Instead of leaving the Battle Zone, flip this Dragheart creature to its lower-cost face.",
        "full_rule_ref": "806.1b",
        "is_replacement": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Forbidden Release",
        "short_desc": "Flip this Forbidden Heartbeat to its forbidden creature face.",
        "full_rule_ref": "701.25a",
        "is_triggered": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Awakening",
        "short_desc": "Flip this Psychic Creature to its other face when the condition is met.",
        "full_rule_ref": "804.1a",
        "is_triggered": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Awakening Link",
        "short_desc": "Flip multiple Psychic Creatures simultaneously to link into a Psychic Super Creature.",
        "full_rule_ref": "804.1c",
        "is_triggered": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Gachinko Judge",
        "short_desc": "Each player reveals the top card; higher mana cost wins.",
        "full_rule_ref": "701.21a",
        "is_activated": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Just Diver",
        "short_desc": "When this creature enters the Battle Zone, it is immune to targeting until the start of your next turn.",
        "full_rule_ref": None,
        "is_triggered": True,
        "is_replacement": False,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "EX Life",
        "short_desc": "When this creature would leave the Battle Zone, put it into your Shield Zone face-down instead.",
        "full_rule_ref": None,
        "is_replacement": True,
        "usable_in_phase": ["any"],
    },
    {
        "name":  "Hyper Mode",
        "short_desc": "Release Hyper Mode to gain extra abilities and power.",
        "full_rule_ref": "816.2",
        "is_activated": True,
        "usable_in_phase": ["any"],
    },
    # ── D-Switch / Field keywords ─────────────────────────────────────────────
    {
        "name":  "D-Switch",
        "short_desc": "Once per game, flip this Field upside-down to activate its D-Switch effect.",
        "full_rule_ref": "308.3",
        "is_activated": True,
        "usable_in_phase": ["any"],
    },
    # ── Abyss keyword ────────────────────────────────────────────────────────
    {
        "name":  "Send to the Abyss",
        "short_desc": "Move a card to the Abyss Zone; it cannot leave for the rest of the game.",
        "full_rule_ref": "701.33a",
        "is_static": True,
        "usable_in_phase": ["any"],
    },
    # ── GR / Oura keywords ────────────────────────────────────────────────────
    {
        "name":  "Aura",
        "short_desc": "Attach to a GR Creature to boost its power and grant abilities.",
        "full_rule_ref": "310.1",
        "is_static": True,
        "usable_in_phase": ["main"],
    },
    {
        "name":  "Kirifudash",
        "short_desc": "After breaking a shield with this creature, if condition met, summon for free.",
        "full_rule_ref": None,
        "is_triggered": True,
        "requires_declaration": False,
        "usable_in_phase": ["attack_end"],
    },
    {
        "name":  "Fushigibirth",
        "short_desc": "Use this card for free by sacrificing a creature of the specified type.",
        "full_rule_ref": "601.1a",
        "is_activated": True,
        "usable_in_phase": ["main"],
    },
]
