"""Fine-tune LFM2.5 JP on parser examples generated by prepare_dataset.py."""

from __future__ import annotations

import argparse
import contextlib
import inspect
import io
import logging
import os
import warnings
from typing import Any
from importlib import import_module


DEFAULT_MODEL_ID = "LiquidAI/LFM2.5-1.2B-JP-202606"
DEFAULT_OUTPUT_DIR = "./lfm25-jp-duelmasters"
DEFAULT_FINAL_DIR = "./lfm25-jp-duelmasters-final"


def _import_training_stack():
    try:
        torch = import_module("torch")
        datasets = import_module("datasets")
        transformers = import_module("transformers")
        peft = import_module("peft")
        trl = import_module("trl")
    except ImportError as exc:
        raise SystemExit(
            "Missing fine-tuning dependency. Install datasets, transformers, peft, trl, "
            "accelerate, bitsandbytes, and torch before running this script. "
            "Unsloth is optional and can speed up supported model families."
        ) from exc
    return torch, datasets, transformers, peft, trl


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Fine-tune LFM2.5 JP for Duel Masters effect parsing")
    parser.add_argument(
        "--model-id", default=os.getenv("FINETUNE_MODEL_ID", DEFAULT_MODEL_ID))
    parser.add_argument(
        "--train-dataset", default=os.getenv("FINETUNE_TRAIN_DATASET", "dm_train"))
    parser.add_argument(
        "--val-dataset", default=os.getenv("FINETUNE_VAL_DATASET", "dm_val"))
    parser.add_argument(
        "--output-dir", default=os.getenv("FINETUNE_OUTPUT_DIR", DEFAULT_OUTPUT_DIR))
    parser.add_argument(
        "--final-dir", default=os.getenv("FINETUNE_FINAL_DIR", DEFAULT_FINAL_DIR))
    parser.add_argument("--epochs", type=float,
                        default=float(os.getenv("FINETUNE_EPOCHS", "3")))
    parser.add_argument("--batch-size", type=int,
                        default=int(os.getenv("FINETUNE_BATCH_SIZE", "4")))
    parser.add_argument("--eval-batch-size", type=int,
                        default=int(os.getenv("FINETUNE_EVAL_BATCH_SIZE", "4")))
    parser.add_argument("--grad-accum", type=int,
                        default=int(os.getenv("FINETUNE_GRAD_ACCUM", "4")))
    parser.add_argument("--learning-rate", type=float,
                        default=float(os.getenv("FINETUNE_LR", "2e-4")))
    parser.add_argument("--warmup-steps", type=int,
                        default=int(os.getenv("FINETUNE_WARMUP_STEPS", "0")))
    parser.add_argument("--max-seq-length", type=int,
                        default=int(os.getenv("FINETUNE_MAX_SEQ_LENGTH", "2048")))
    parser.add_argument("--logging-steps", type=int,
                        default=int(os.getenv("FINETUNE_LOGGING_STEPS", "20")))
    parser.add_argument("--eval-steps", type=int,
                        default=int(os.getenv("FINETUNE_EVAL_STEPS", "100")))
    parser.add_argument("--save-steps", type=int,
                        default=int(os.getenv("FINETUNE_SAVE_STEPS", "200")))
    parser.add_argument("--save-total-limit", type=int,
                        default=int(os.getenv("FINETUNE_SAVE_TOTAL_LIMIT", "3")))
    parser.add_argument("--lora-r", type=int,
                        default=int(os.getenv("FINETUNE_LORA_R", "16")))
    parser.add_argument("--lora-alpha", type=int,
                        default=int(os.getenv("FINETUNE_LORA_ALPHA", "32")))
    parser.add_argument("--lora-dropout", type=float,
                        default=float(os.getenv("FINETUNE_LORA_DROPOUT", "0.05")))
    parser.add_argument(
        "--target-modules",
        default=os.getenv("FINETUNE_TARGET_MODULES",
                          "q_proj,k_proj,v_proj,o_proj"),
        help="Comma-separated LoRA target module names",
    )
    parser.add_argument("--seed", type=int,
                        default=int(os.getenv("FINETUNE_SEED", "1")))
    parser.add_argument("--weight-decay", type=float,
                        default=float(os.getenv("FINETUNE_WEIGHT_DECAY", "0.0")))
    parser.add_argument("--max-grad-norm", type=float,
                        default=float(os.getenv("FINETUNE_MAX_GRAD_NORM", "0.3")))
    parser.add_argument("--no-4bit", action="store_true",
                        help="Disable 4-bit quantized loading")
    parser.add_argument("--no-gradient-checkpointing", action="store_true")
    parser.add_argument("--fp16", action="store_true",
                        help="Use fp16 instead of bf16 in trainer config")
    parser.add_argument("--hf-token", default=os.getenv("HF_TOKEN"),
                        help="Optional Hugging Face token; avoids unauthenticated Hub warnings")
    return parser


def _format_messages(example: dict[str, Any], tokenizer) -> dict[str, str]:
    messages = example["messages"]
    if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False)
    else:
        text = "\n".join(
            f"{message['role']}: {message['content']}" for message in messages)
    return {"text": text}


def _quiet_library_warnings() -> None:
    """Suppress noisy dependency warnings that do not affect training."""
    os.environ.setdefault("HF_HUB_DISABLE_TELEMETRY", "1")
    warnings.filterwarnings("ignore", category=FutureWarning, module=r"bitsandbytes.*")
    warnings.filterwarnings("ignore", message=r".*_check_is_size.*")
    warnings.filterwarnings("ignore", message=r".*warmup_ratio is deprecated.*")
    logging.getLogger("huggingface_hub").setLevel(logging.ERROR)
    logging.getLogger("transformers").setLevel(logging.ERROR)
    logging.getLogger("bitsandbytes").setLevel(logging.ERROR)
    logging.getLogger("datasets").setLevel(logging.ERROR)


def _supported_kwargs(callable_obj, kwargs: dict[str, Any]) -> dict[str, Any]:
    """Keep only kwargs accepted by the installed library version."""
    params = inspect.signature(callable_obj).parameters
    if any(param.kind == inspect.Parameter.VAR_KEYWORD for param in params.values()):
        return kwargs
    return {key: value for key, value in kwargs.items() if key in params}


def _strategy_kwargs(config_cls, *, has_eval: bool, eval_steps: int) -> dict[str, Any]:
    params = inspect.signature(config_cls).parameters
    value = "steps" if has_eval else "no"
    if "eval_strategy" in params:
        return {"eval_strategy": value, "eval_steps": eval_steps}
    if "evaluation_strategy" in params:
        return {"evaluation_strategy": value, "eval_steps": eval_steps}
    return {}


def _precision_settings(torch, *, prefer_fp16: bool) -> dict[str, Any]:
    cuda_available = bool(torch.cuda.is_available())
    bf16_supported = bool(
        cuda_available
        and hasattr(torch.cuda, "is_bf16_supported")
        and torch.cuda.is_bf16_supported()
    )
    use_bf16 = cuda_available and bf16_supported and not prefer_fp16
    use_fp16 = cuda_available and not use_bf16
    compute_dtype = (
        torch.bfloat16
        if use_bf16
        else torch.float16 if use_fp16 else torch.float32
    )
    return {
        "cuda_available": cuda_available,
        "bf16": use_bf16,
        "fp16": use_fp16,
        "use_cpu": not cuda_available,
        "compute_dtype": compute_dtype,
    }


def _bitsandbytes_is_usable(torch) -> bool:
    """Return False when bitsandbytes imports but CUDA quantization is broken."""
    try:
        with contextlib.redirect_stderr(io.StringIO()), contextlib.redirect_stdout(io.StringIO()):
            bnb = import_module("bitsandbytes")
            cextension = import_module("bitsandbytes.cextension")
            if torch.cuda.is_available():
                probe = torch.zeros((16, 16), device="cuda", dtype=torch.float16)
                bnb.functional.quantize_4bit(probe, quant_type="nf4")
    except Exception:
        return False
    return getattr(cextension, "lib", None) is not None and bnb is not None


def _load_model_with_optional_quantization(
    transformers,
    *,
    model_id: str,
    quantization_config,
    model_load_kwargs: dict[str, Any],
):
    try:
        return transformers.AutoModelForCausalLM.from_pretrained(
            model_id,
            quantization_config=quantization_config,
            device_map="auto",
            **model_load_kwargs,
        ), quantization_config is not None
    except Exception as exc:
        if quantization_config is None:
            raise
        message = str(exc)
        if "bitsandbytes" not in message and "Bnb4bit" not in message and "libnvJitLink" not in message:
            raise
        print("4-bit quantization failed during model load; retrying without bitsandbytes.")
        return transformers.AutoModelForCausalLM.from_pretrained(
            model_id,
            device_map="auto",
            **model_load_kwargs,
        ), False


def main() -> None:
    args = _build_parser().parse_args()
    _quiet_library_warnings()
    torch, datasets, transformers, peft, trl = _import_training_stack()
    transformers.set_seed(args.seed)
    precision = _precision_settings(torch, prefer_fp16=args.fp16)
    use_4bit = bool(
        not args.no_4bit
        and precision["cuda_available"]
        and _bitsandbytes_is_usable(torch)
    )
    if not args.no_4bit and not use_4bit:
        print("4-bit quantization disabled: CUDA/bitsandbytes native library is unavailable.")

    model_load_kwargs = {"token": args.hf_token} if args.hf_token else {}
    tokenizer = transformers.AutoTokenizer.from_pretrained(args.model_id, **model_load_kwargs)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    quantization_config = None
    if use_4bit:
        quantization_config = transformers.BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=precision["compute_dtype"],
            bnb_4bit_use_double_quant=True,
        )

    model, use_4bit = _load_model_with_optional_quantization(
        transformers,
        model_id=args.model_id,
        quantization_config=quantization_config,
        model_load_kwargs=model_load_kwargs,
    )
    model.config.use_cache = False
    if not args.no_gradient_checkpointing:
        model.gradient_checkpointing_enable()
    if use_4bit and hasattr(peft, "prepare_model_for_kbit_training"):
        model = peft.prepare_model_for_kbit_training(
            model,
            use_gradient_checkpointing=not args.no_gradient_checkpointing,
        )

    target_modules = [module.strip()
                      for module in args.target_modules.split(",") if module.strip()]
    lora_config = peft.LoraConfig(
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        target_modules=target_modules,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=peft.TaskType.CAUSAL_LM,
    )
    model = peft.get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    train_ds = datasets.load_from_disk(args.train_dataset)
    val_ds = datasets.load_from_disk(args.val_dataset)
    train_ds = train_ds.map(lambda example: _format_messages(
        example, tokenizer), remove_columns=train_ds.column_names)
    val_ds = val_ds.map(lambda example: _format_messages(
        example, tokenizer), remove_columns=val_ds.column_names)
    has_eval = len(val_ds) > 0

    config_kwargs = {
        "output_dir": args.output_dir,
        "num_train_epochs": args.epochs,
        "per_device_train_batch_size": args.batch_size,
        "per_device_eval_batch_size": args.eval_batch_size,
        "gradient_accumulation_steps": args.grad_accum,
        "learning_rate": args.learning_rate,
        "weight_decay": args.weight_decay,
        "max_grad_norm": args.max_grad_norm,
        "lr_scheduler_type": "cosine",
        "warmup_steps": args.warmup_steps,
        "logging_steps": args.logging_steps,
        "save_strategy": "steps",
        "save_steps": args.save_steps,
        "save_total_limit": args.save_total_limit,
        "load_best_model_at_end": has_eval,
        "bf16": precision["bf16"],
        "fp16": precision["fp16"],
        "use_cpu": precision["use_cpu"],
        "max_seq_length": args.max_seq_length,
        "dataset_text_field": "text",
        "report_to": "none",
        "gradient_checkpointing": not args.no_gradient_checkpointing,
        "optim": "paged_adamw_8bit" if use_4bit else "adamw_torch",
        **_strategy_kwargs(trl.SFTConfig, has_eval=has_eval, eval_steps=args.eval_steps),
    }
    sft_config = trl.SFTConfig(**_supported_kwargs(trl.SFTConfig, config_kwargs))

    trainer_kwargs = {
        "model": model,
        "args": sft_config,
        "train_dataset": train_ds,
        "eval_dataset": val_ds if has_eval else None,
        "processing_class": tokenizer,
        "tokenizer": tokenizer,
        "max_seq_length": args.max_seq_length,
        "dataset_text_field": "text",
    }
    trainer = trl.SFTTrainer(**_supported_kwargs(trl.SFTTrainer, trainer_kwargs))

    trainer.train()
    trainer.save_model(args.final_dir)
    tokenizer.save_pretrained(args.final_dir)


if __name__ == "__main__":
    main()
